--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15/01/2016 15:03:03
-- Server version: 5.6.26-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE mercado_v2;

--
-- Definition for table clientes
--
DROP TABLE IF EXISTS clientes;
CREATE TABLE clientes (
  cli_id INT(11) NOT NULL AUTO_INCREMENT,
  cli_nome VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (cli_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table produtos
--
DROP TABLE IF EXISTS produtos;
CREATE TABLE produtos (
  pro_id INT(11) NOT NULL AUTO_INCREMENT,
  pro_nome VARCHAR(255) DEFAULT NULL,
  pro_valor DOUBLE(15, 2) DEFAULT 0.00,
  PRIMARY KEY (pro_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 8
AVG_ROW_LENGTH = 2340
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table itens
--
DROP TABLE IF EXISTS itens;
CREATE TABLE itens (
  itens_id INT(11) NOT NULL AUTO_INCREMENT,
  itens_produto INT(11) DEFAULT NULL,
  itens_cod_venda VARCHAR(20) DEFAULT NULL,
  itens_qtd INT(11) DEFAULT NULL,
  PRIMARY KEY (itens_id),
  CONSTRAINT FK_itens_produtos_pro_id FOREIGN KEY (itens_produto)
    REFERENCES produtos(pro_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table pedidos
--
DROP TABLE IF EXISTS pedidos;
CREATE TABLE pedidos (
  ped_id INT(11) NOT NULL AUTO_INCREMENT,
  ped_data DATE DEFAULT NULL,
  ped_cliente INT(11) DEFAULT NULL,
  ped_codigo VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ped_id),
  CONSTRAINT FK_pedidos_clientes_cli_id FOREIGN KEY (ped_cliente)
    REFERENCES clientes(cli_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for view view_pedidos
--
DROP VIEW IF EXISTS view_pedidos CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW view_pedidos
AS
	select `clientes`.`cli_nome` AS `cli_nome`,`itens`.`itens_qtd` AS `itens_qtd`,`pedidos`.`ped_data` AS `ped_data`,`pedidos`.`ped_codigo` AS `ped_codigo`,`produtos`.`pro_nome` AS `pro_nome`,`produtos`.`pro_valor` AS `pro_valor` from (((`clientes` join `itens`) join `pedidos`) join `produtos`) where ((`clientes`.`cli_id` = `pedidos`.`ped_cliente`) and (`itens`.`itens_cod_venda` = `pedidos`.`ped_codigo`) and (`itens`.`itens_produto` = `produtos`.`pro_id`));

-- 
-- Dumping data for table clientes
--
INSERT INTO clientes VALUES
(1, 'jose'),
(2, 'fernando'),
(3, 'maria'),
(4, 'bob');

-- 
-- Dumping data for table produtos
--
INSERT INTO produtos VALUES
(1, 'bolacha', 2.30),
(2, 'biscoito sem sal', 1.50),
(3, 'macarao branco', 3.25),
(4, 'molho de tomate', 3.40),
(5, 'leite de caixinha', 2.85),
(6, 'pao doce', 1.23),
(7, 'apresuntado master', 1.00);

-- 
-- Dumping data for table itens
--
INSERT INTO itens VALUES
(1, 2, '0001', 3),
(2, 1, '0001', 1),
(3, 2, '0002', 2),
(4, 4, '0002', 5);

-- 
-- Dumping data for table pedidos
--
INSERT INTO pedidos VALUES
(5, '2016-01-14', 3, '0001'),
(6, '2016-01-14', 4, '0002');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;