--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.358.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15/01/2016 15:02:43
-- Server version: 5.6.26-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE mercado;

--
-- Definition for table compras
--
DROP TABLE IF EXISTS compras;
CREATE TABLE compras (
  nome VARCHAR(30) DEFAULT NULL,
  description VARCHAR(30) DEFAULT NULL,
  valor DOUBLE(15, 2) DEFAULT NULL
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2048
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table vendas
--
DROP TABLE IF EXISTS vendas;
CREATE TABLE vendas (
  nome VARCHAR(30) DEFAULT NULL,
  date DATE DEFAULT NULL,
  valor DOUBLE(2, 1) DEFAULT NULL
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table compras
--
INSERT INTO compras VALUES
('americo', 'pao', 1.00),
('ana', 'fruta', 2.00),
('jose', 'desodorizante', 2.00),
('maria', 'massa de tomate', 2.00),
('jose', 'sal grosso', 4.00),
('fernando', 'manteiga', 5.00),
('maria', 'sal grosso', 2.00),
('fernando', 'pao doce', 3.00);

-- 
-- Dumping data for table vendas
--

-- Table mercado.vendas does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;